version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spend_smart
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  postgres_data: