version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spend_smart
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  mysql_data:
